node {
    def app

    stage('Clone repository') {
        /* Let's make sure we have the repository cloned to our workspace */

        checkout scm
    }
    stage('Build UI') {
        docker.image('docker.registry/maven:3-alpine').inside('-v $HOME/.m2:/root/.m2') {
            sh 'mvn clean package spring-boot:repackage'
        }
    }

    stage('Build image') {
        /* This builds the actual image; synonymous to
         * docker build on the command line */

        app = docker.build("docker.registry/uaas-java")
    }

    stage('Push image') {
        /* Finally, we'll push the image into Docker Hub */

        docker.withRegistry('http://docker.registry', 'docker-registry-credentials') {
            app.push("latest")
        }
    }
}