node {
    def app

    stage('Clone repository') {
        /* Let's make sure we have the repository cloned to our workspace */

        checkout scm
    }

    stage('Build UI') {
        docker.image('docker.sense.io/mvn-jdk8:3.6.1').inside('-v /var/jenkins_home/.m2:/home/maven/.m2') {
            sh 'mvn clean compile package spring-boot:repackage -U '
        }
    }

    stage('SonarQube analysis') {
        def sonarqubeScannerHome = tool name: 'SonarQubeScanner'

        withSonarQubeEnv('SonarQube') {
            sh "${sonarqubeScannerHome}/bin/sonar-scanner"
        }
    }


    stage('Build image') {
        /* This builds the actual image; synonymous to
         * docker build on the command line */

        app = docker.build('docker.sense.io/uaas-java')
    }

    stage('Push image') {
        /* Finally, we'll push the image into Docker Hub */

        docker.withRegistry('http://docker.sense.io', 'docker.sense.io-credentials') {
            app.push("latest")
        }
    }
}